snflake_test:
  outputs:
    dev:
      account: bf05262.us-central1.gcp
      database: ANALYTICS_DEV
      password: "{{ env_var('DBT_PASSWORD_SNFLAKE') }}"
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER_SNFLAKE') }}"
      warehouse: DBT_DEMO_WH
    prod:
      account: bf05262.us-central1.gcp
      database: ANALYTICS_DEV
      password: "{{ env_var('DBT_PASSWORD_SNFLAKE') }}"
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER_SNFLAKE') }}"
      warehouse: DBT_DEMO_WH
  target: dev
