# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DBT_USER_SNFLAKE: ${{ secrets.DBT_USER_SNFLAKE }}
      DBT_PASSWORD_SNFLAKE: ${{ secrets.DBT_PASSWORD_SNFLAKE }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
           python-version: '3.10' 
      
      - name: Insatll dbt
        run: pip install dbt-snowflake
        
      - name: Run dbt deps
        run: dbt build --profiles-dir .
      
      - name: Run dbt build
        run: dbt build --profiles-dir .
        
